name: Package Application with PyInstaller on Staging
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: >
          python -m pip install --upgrade pip

          pip install -r requirements.txt

      - name: Package Application with PyInstaller
        run: |
          pyinstaller main.py --name staging_sepreadsheet_separator_app --onedir --additional-hooks-dir=./hooks --collect-all streamlit --hidden-import "streamlit.web.cli" --add-data "streamlit_app.py;." --add-data ".streamlit/config.toml;.streamlit/" --clean --noconfirm

      - name: Zip the Build
        run: Compress-Archive -Path dist/staging_sepreadsheet_separator_app -DestinationPath dist/staging_sepreadsheet_separator_app.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App-Zip
          path: dist/staging_sepreadsheet_separator_app.zip
          retention-days: 14